spring.datasource.url=jdbc:postgresql://getpet_db:5432/getpet
spring.datasource.username=getpet
spring.datasource.password=getpet
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8080
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=method
springdoc.swagger-ui.operations-sorter=method
api.security.token.secret=${JWT_SECRET:my-secret-key}

minio.internal-endpoint=${MINIO_INTERNAL_ENDPOINT}
minio.public-endpoint=${MINIO_PUBLIC_URL}
minio.secure=false
minio.external-url=http://localhost:9000
minio.url=http://minio:9000       # URL interna usada dentro do docker
minio.public-url=http://localhost:9000   # URL externa usada pelo navegador
minio.bucket-name=fotos-app
minio.access-key=minioadmin
minio.secret-key=minioadmin