services:
  db:
    image: postgres:16
    container_name: getpet_db
    restart: always
    environment:
      POSTGRES_USER: getpet
      POSTGRES_PASSWORD: getpet
      POSTGRES_DB: getpet
    networks:
      - app-network
    ports:
      - "5432:5432"
  api:
    build:
      context: ./back-facilita_ai
    container_name: getpet_api
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: getpet
      DATABASE_PASSWORD: getpet
      DATABASE_NAME: getpet
    networks:
      - app-network
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ../FRONT-Facilita-ai
    container_name: getpet_frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge